{% set version = "2.0.18" %}

package:
  name: bob.blitz
  version: {{ version }}

source:
  fn: bob.blitz-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.blitz/bob.blitz-{{ version }}.zip
  md5: 4bb37b26ab0b57e31e909fa7792664bc

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - numpy x.x
    - pkg-config
    - libblitz 0.10|0.10.*
    - boost 1.63.*
    - cmake

  run:
    - python
    - bob.extension
    - numpy x.x
    - libblitz 0.10|0.10.*
    - boost 1.63.*

test:
  requires:
    - nose

  imports:
    - bob
    - bob.blitz

  commands:
    - nosetests -sv bob.blitz

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-Clause
  summary: Bindings for Blitz++ (a C++ array template library)

extra:
  recipe-maintainers:
    - 183amir
